#+TITLE:  EOS-OS
#+AUTHOR: Chris Smeele

(this is a work in progress)

** Dependencies

- nasm
- lld
- llvm
- clang
- parted
- qemu (if you are running with QEMU)
- bochs (if you are running with Bochs)

** Repo structure

| *Directory*   | *Description*                      |
|---------------|------------------------------------|
| ~/boot~       | Bootloader (bootsector and stage2) |
| ~/boot/utils~ | Bootloader installer               |
| ~/kernel~     | Kernel code                        |

| *Makefile*               | *Description*                                            |
|--------------------------|----------------------------------------------------------|
| ~/Makefile~              | Builds everything, creates boot disks and runs emulators |
| ~/boot/Makefile~         | Builds bootloader and installer                          |
| ~/kernel/Makefile~       | Builds kernel                                            |

Every Makefile above includes (if available) a ~Makefile.local~ file in the
same directory. This allows you to override any toolchain executable names and
paths, and to optionally add additional targets.

** How to build / run

Do not forget to pass ~-j 4~ (or higher) to make to increase build performance
on multicore systems.

*** QEMU

This builds the kernel and bootloader and creates a boot disk that is run with
QEMU:

: make disk && make run

To enable acceleration using kvm, run:

: make disk && make qemu-kvm

*** Forcing a rebuild

This forcibly rebuilds all components, ignoring existing output files.

: make rebuild

*** Debugging

You can debug the kernel with either QEMU or Bochs:

- QEMU/gdb: Provides a familiar debugger interface with good C++ integration.
- Bochs: Provides a better low-level overview with good x86 error reporting, runs slower.

**** QEMU/gdb

See [[./gdbrc]] for startup options (you may override this file path in a ~Makefile.local~).

: make disk && make debug

See [[./bochsrc]] for configuration options (you may override this file path in a ~Makefile.local~).

**** Bochs

: make disk && make bochs
